# Generated by Django 4.2.5 on 2023-10-08 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_api", "0003_alter_comissionmodel_day_comission_perc_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_numeric_value",
                                message="Only numeric characters are allowed.",
                                regex="^[0-9]+$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=10,
                                message="Invoice must have only 10 characters.",
                            ),
                        ],
                    ),
                ),
                ("sell_date", models.DateTimeField(null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="base_api.clientmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="product_sellproduct",
                        to="base_api.productmodel",
                    ),
                ),
                (
                    "sell_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sell_sellproduct",
                        to="base_api.sellmodel",
                    ),
                ),
            ],
            options={
                "db_table": "sell_product",
                "unique_together": {("product_id", "sell_id")},
            },
        ),
        migrations.AddField(
            model_name="sellmodel",
            name="products",
            field=models.ManyToManyField(
                through="base_api.SellProductModel", to="base_api.productmodel"
            ),
        ),
        migrations.AddField(
            model_name="sellmodel",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="base_api.sellermodel",
            ),
        ),
    ]
