# Generated by Django 4.2.5 on 2023-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_api", "0004_sellmodel_sellproductmodel_sellmodel_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellproductmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
