# Generated by Django 4.2.5 on 2023-10-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_api", "0005_alter_sellproductmodel_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellproductmodel",
            name="product_id",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_sellproduct",
                to="base_api.productmodel",
            ),
        ),
    ]
