# Generated by Django 4.2.5 on 2023-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_api", "0008_alter_productmodel_comis_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellmodel",
            name="deleted",
            field=models.BooleanField(default=0),
        ),
    ]
